services:
  bdd-build:
    container_name: bdd_build
    image: mariadb:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: bddname
      MYSQL_USER: roger
      MYSQL_PASSWORD: regor
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 10s
      retries: 3

  backend-build:
    container_name: backend_build
    build: .
    depends_on:
      bdd-build:
        condition: service_healthy
    environment:
      BDD_HOST: bdd-build
    ports:
      - 23000:23000