name: Integration
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Backend:
    if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.head.ref, '#useless')}}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: toor
          MARIADB_DATABASE: test
          MARIADB_USER: test
          MARIADB_PASSWORD: test
        ports:
          - 3306:3306
        options: --health-cmd="health.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3